
name: CI/CD Pipeline for mytestdevopsapp

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t myfirstdevopsapp .

      - name: Run Docker container
        run: docker run -p 5000:80 myfirstdevopsapp
